🚀 3단계 - Transaction 적용하기
next-step/java-jdbc pull request #14
Opened 2024-08-14 12:38 UTC by SeolYoungKim

안녕하세요 동철님! 
이번 미션도 잘 부탁드립니다! 

만들다 보니 4단계 미션에서 사용하라고 명시되어 있는 DatasourceUtils와 비슷한 ConnectionUtils를 만들어 버렸는데, 그냥 DatasourceUtils를 사용할까 하다가, 4단계 미션에서 사용하라고 되어있어서 제가 구현한 ConnectionUtils를 사용하고 있는 점 참고 부탁드립니다!

2024-08-15 08:38 UTC, sah3122 requested changes
트랜젝션 구현 잘해주셨습니다 👍 
미션의 요구사항은 만족하지만 조금더 학습하기 위해 한가지 도전과제를 남겨두었는데 확인 부탁드려요 !

2024-08-15 08:38 UTC, sah3122 commented on app/src/main/java/camp/nextstep/service/UserService.java
> +    private void targetMethod(long id, String newPassword, String createBy) {
트랜젝션을 적용할때마다 대상 메서드를 이처럼 분리 해줘야 한다면 사용자가 사용하기 어려울것 같습니다 😄

2024-08-15 08:38 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/transaction/TransactionHandler.java
> +    public void executeWithTransaction(DataSource dataSource, TransactionCallback txCallback) {
명시적인 트랜젝션 영역을 표시하도록 구현 잘해주셨습니다 👍 
조금더 나아가서 Tx의 시작과 끝을 사용자가 관리 할수 있도록 메서드를 추가해보는건 어떨까요 ?
앞선 코멘트의 해결법이 될수 있을것 같아요 😄

2024-08-15 08:38 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +        if (TransactionSynchronizationManager.isTransactionActive(dataSource)) {
이번 미션에서 TransactionSynchronizationManager를 사용하는것은 요구되지 않았는데 미리 구현 잘해주셨습니다 👍

2024-08-15 08:38 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +        }
커넥션을 종료하지 못하는 경우도 사용자에게 알려주는건 어떨까요 ?

2024-08-15 08:38 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/jdbc/core/JdbcTemplate.java
> +            connection = ConnectionUtils.getConnection(dataSource);
동일한 커넥션을 사용할수 있도록 Util을 통한 접근 👍

2024-08-15 08:38 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +            return TransactionSynchronizationManager.getResource(dataSource);
이미 TransactionSynchronizationManager를 활용해주셧네요 👍 
이처럼 커넥션과 같은 리소스는 스레드간 공유를 하기 때문에 ThreadLocal을 활용하여 관리하는것이 효율적입니다. 
ThreadLocal을 경험하지 못하였다면 이번 기회에 조금더 학습해보는것도 좋을것 같아요 😄

2024-08-15 10:36 UTC, SeolYoungKim commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +        }
close() 메서드 내부에서 CannotCloseJdbcConnectionException 을 통해 알려주도록 하고 있는데, 혹시 이걸로는 부족할까요?

2024-08-15 11:03 UTC, SeolYoungKim commented on app/src/main/java/camp/nextstep/service/UserService.java
> +    private void targetMethod(long id, String newPassword, String createBy) {
헙 그러네요. 이렇게 되면 사용이 매우 불편할 것 같다는 생각을 하지 못했네요. 😅 라이브러리나 프레임워크 구현자들은 이런 부분들도 다 생각을 해서 설계를 했을텐데, 새삼 대단해 보입니다. 

동철님 덕분에 사용자 측면을 고려하는 방법을 배워갑니다 👍

2024-08-15 11:03 UTC, SeolYoungKim commented on jdbc/src/main/java/camp/nextstep/transaction/TransactionHandler.java
> +    public void executeWithTransaction(DataSource dataSource, TransactionCallback txCallback) {
나름 개선을 시도해보았습니다! 감사합니다 ☺️

2024-08-15 11:34 UTC, SeolYoungKim commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +            return TransactionSynchronizationManager.getResource(dataSource);
감사합니다! 689f8eee 커밋에 학습 테스트 한번 작성 해봤습니다 😄

2024-08-15 11:35 UTC, SeolYoungKim commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +        if (TransactionSynchronizationManager.isTransactionActive(dataSource)) {
뭔가 Connection을 계속 넘겨서 전파하는 것이 불편하고 이상하다고 생각해서 방법을 찾다보니 결국 이 방법을 쓰게되더라구요! TransactionSynchronizationManager가 있어야 하는 이유를 더 잘 알게된 것 같습니다 😄

2024-08-16 07:43 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
다음 미션도 화이팅 해주세요 !

2024-08-16 07:43 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/transaction/TransactionHandler.java
> +    public void begin(DataSource dataSource) {
피드백 반영 잘해주셨습니다 👍

2024-08-16 07:43 UTC, sah3122 commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +        }
남겨놓은 코멘트의 의도는 closeConnection() 메서드를 호출해도 커넥션이 없거나 활성화된 트랜젝션이 있는 경우 종료되지 못하도록 정의가 되어 있습니다. 
두 조건에 맞지 않으면 아무런 행위를 하지 않고 있는데 사용자에게 이유를 알려주는것이 어떤지에 대한 코멘트였습니다 😄

2024-08-16 07:43 UTC, merged

2024-08-16 11:44 UTC, SeolYoungKim commented on jdbc/src/main/java/camp/nextstep/jdbc/datasource/ConnectionUtils.java
> +        }
아하..! 제가 깊은 뜻을 헤아리질 못했습니다.😓 저는 커넥션이 종료되지 못하는 경우가 close 시도를 실패하는 경우만 있다고 생각했는데, 다시 한번 돌아보니 동철님이 말씀하신 케이스에 대한 경우도 있었네요! 이를 알려주기 위해 어떤 방법이 있을까 고민 해보았는데, 트랜잭션에 참여중이므로 커넥션을 닫지 않는다는 정보를 알려주는 로그 메세지를 출력 해주거나, 좀 더 엄격하게 제한하고 싶을 경우 예외를 발생시키는 방법을 생각 해보았습니다.